name: csvtokmz-ge-aqpro
channels:
  - conda-forge
dependencies:
  - black
  - gdal
  - geopandas
  - geoviews
  - ipykernel
  - jupyterlab
  - pandas
  - pip
  - python=3.11
  - ruff
  - shapely
  - simplekml
  - typer
  - openpyxl
